Repository Daily-DAYO/DAYO_Android, pull requests merged in 2021-12, with the labels that each got.

#67 #66 [feature] Apply Hilt, Retrofit2 base
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapater.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt
  app/src/main/java/com/daily/dayo/repository/HomeRepository.kt
  app/src/main/java/com/daily/dayo/util/Resource.kt
  app/src/main/res/layout/item_main_post.xml
Labels: feature

#69 #68 [feature] DayoPickPostListFragment, ResponsePostModel
  app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt
  app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/item_main_post.xml
Labels: feature

#70 #60 [ feature] FolderAddFragment, SharedPreferences
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/daily/dayo/DayoApplication.kt
  app/src/main/java/com/daily/dayo/PreferenceHelper.kt
  app/src/main/java/com/daily/dayo/SharedManager.kt
  app/src/main/java/com/daily/dayo/User.kt
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/login/LoginActivity.kt
  app/src/main/java/com/daily/dayo/login/LoginRepository.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt
  app/src/main/java/com/daily/dayo/network/login/LoginService.kt
  app/src/main/java/com/daily/dayo/network/login/LoginServiceImpl.kt
  app/src/main/java/com/daily/dayo/profile/FolderAddFragment.kt
  app/src/main/java/com/daily/dayo/profile/FolderAddViewModel.kt
  app/src/main/java/com/daily/dayo/profile/model/ResponseFolder.kt
  app/src/main/java/com/daily/dayo/repository/FolderRepository.kt
  app/src/main/res/layout/fragment_folder_add.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/xml/network_security_config.xml
Labels: feature

#74 #71 [layout] MyProfileEditFragment
  app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt
  app/src/main/res/drawable/ic_camera_button.xml
  app/src/main/res/drawable/ic_user_profile_image_empty.xml
  app/src/main/res/layout/fragment_my_profile_edit.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: layout

#75 #73 [bug] Remove double quotes
  app/src/main/java/com/daily/dayo/di/NetworkModule.kt
Labels: bug
