Repository Daily-DAYO/DAYO_Android, pull requests merged in 2022-11, with the labels that each got.

#329 #328 [feature] Create Loading Dialog in WriteOptionFragment
  app/src/main/java/com/daily/dayo/common/dialog/DefaultDialog.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
Labels: feature, layout

#330 #324 [layout] Change SwipeRefreshLayout in Home, Feed Fragment
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml
  app/src/main/res/layout/fragment_home_new_post_list.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_feed_post.xml
Labels: layout

#335 #333 [feature] Create PolicyFragment
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/policy/PolicyFragment.kt
  app/src/main/res/drawable/ic_dayo_loading.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_policy.xml
  app/src/main/res/navigation/nav_graph_login.xml
  app/src/main/res/values/strings.xml
Labels: feature, layout

#336 #334 [feature] Show LoadingDialog during POST Networking
  app/src/main/java/com/daily/dayo/common/dialog/LoadingAlertDialog.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordConfirmationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginEmailFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionMineFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/report/ReportPostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/report/ReportUserFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordNewFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/withdraw/WithdrawFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt
Labels: feature

#338 #337 [feature] Add Animation when Navigate
  app/src/main/res/anim/translate_from_left_in.xml
  app/src/main/res/anim/translate_from_right_in.xml
  app/src/main/res/anim/translate_nothing.xml
  app/src/main/res/anim/translate_to_left_out.xml
  app/src/main/res/anim/translate_to_right_out.xml
  app/src/main/res/layout/fragment_folder_setting.xml
  app/src/main/res/layout/fragment_folder_setting_add.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/fragment_profile_edit.xml
  app/src/main/res/layout/fragment_write_option.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature, layout

#340 #339 [feature] Add Sentry Logging
  .gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/resources/sentry.properties
  build.gradle
  sentry.properties
Labels: feature

#342 #341 [bug] Error when modifying, deleting post and folder
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
Labels: bug
