Repository Daily-DAYO/DAYO_Android, pull requests merged in 2022-09, with the labels that each got.

#291 #290 [bug] Fix Adding Tag Error, Edit Post Error, Image Upload Count Error, Remove the Do not post empty settings
  app/src/main/java/com/daily/dayo/common/ListLiveData.kt
  app/src/main/java/com/daily/dayo/common/ReplaceUnicode.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/post/PostResponse.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
Labels: bug, feature

#292 #278 [bug] Update Like Error
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml
  app/src/main/res/layout/fragment_home_new_post_list.xml
Labels: bug

#293 #280 [bug] Time Display Bug
  app/src/main/java/com/daily/dayo/common/TimeChangerUtil.kt
  app/src/main/res/values/strings.xml
Labels: bug

#294 #246 [bug] Not Showing Recent SearchKeyword
  app/src/main/java/com/daily/dayo/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt
  app/src/main/res/drawable/ic_search_result_empty.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/values/strings.xml
Labels: bug, layout

#297 #295 [bug] FindAccountPasswordCheckEmail Fragment Help Message
  app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt
  app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/member/RequestCheckEmailAuthUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCheckEmailCertificateFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
Labels: bug

#298 #284 [feature] Report User and Post
  app/src/main/java/com/daily/dayo/data/datasource/remote/report/ReportApiService.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/report/ReportRequest.kt
  app/src/main/java/com/daily/dayo/data/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/data/repository/ReportRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/ReportRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/report/RequestSaveMemberReportUseCase.kt
  app/src/main/java/com/daily/dayo/domain/usecase/report/RequestSavePostReportUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostReportFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/report/ReportPostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/report/ReportUserFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ReportViewModel.kt
  app/src/main/res/drawable/selector_edittext_report.xml
  app/src/main/res/drawable/selector_radiobutton_report.xml
  app/src/main/res/drawable/selector_radiobutton_report_text.xml
  app/src/main/res/layout/fragment_post_report.xml
  app/src/main/res/layout/fragment_report_post.xml
  app/src/main/res/layout/fragment_report_user.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#300 #299 [refactoring] Upload Resized Image
  app/src/main/java/com/daily/dayo/common/ConvertDP.kt
  app/src/main/java/com/daily/dayo/common/ImageResizeUtil.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt
Labels: bug, refactoring

#304 #303 [bug] Fix ProfileFragment Option Button
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
Labels: bug

#305 #302 [feature] Change Notification Confirmation Logic
  app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/NotificationViewModel.kt
Labels: feature

#308 #301 [bug] FolderFragment RecyclerView ConstraintMissing
  app/src/main/res/layout/fragment_folder.xml
Labels: bug
