Repository Daily-DAYO/DAYO_Android, pull requests merged in 2022-01, with the labels that each got.

#77 #72 [feature] MyProfileEditFragment Image Gallery
  app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileEditImageOptionFragment.kt
  app/src/main/res/layout/fragment_my_profile_edit.xml
  app/src/main/res/layout/fragment_my_profile_edit_image_option.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#79 #78 [layout] DefaultDialogAlert
  app/src/main/java/com/daily/dayo/util/DefaultDialog.kt
  app/src/main/java/com/daily/dayo/write/WriteFragment.kt
  app/src/main/res/drawable/dialog_alert_default.xml
  app/src/main/res/drawable/ic_alert.xml
  app/src/main/res/layout/dialog_default_alert.xml
  app/src/main/res/values/strings.xml
Labels: layout

#80 #76 [layout] FolderSettingFragment
  app/src/main/java/com/daily/dayo/profile/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/profile/FolderSettingFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderAddFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderAddViewModel.kt
  app/src/main/res/drawable/ic_option_horizontal.xml
  app/src/main/res/drawable/selector_default_folder_thumbnail.xml
  app/src/main/res/layout/fragment_folder_setting.xml
  app/src/main/res/layout/fragment_folder_setting_add.xml
  app/src/main/res/layout/fragment_write_folder_add.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#83 #82 [layout] DefaultDialogConfirm
  app/src/main/java/com/daily/dayo/util/DefaultDialog.kt
  app/src/main/java/com/daily/dayo/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt
  app/src/main/res/layout/dialog_default_confirm.xml
  app/src/main/res/values/strings.xml
Labels: layout

#84 #81 [feature] ProfileFolderListFragment
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt
  app/src/main/java/com/daily/dayo/profile/adapter/MyProfileFragmentPagerStateAdapter.kt
  app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/model/Folder.kt
  app/src/main/java/com/daily/dayo/profile/model/ResponseFolder.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt
  app/src/main/java/com/daily/dayo/repository/FolderRepository.kt
  app/src/main/res/layout/fragment_profile_folder_list.xml
  app/src/main/res/layout/item_profile_folder.xml
Labels: feature

#88 #86 [layout] MyProfileOptionFragment
  app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileOptionFragment.kt
  app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderAddFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/write/adapter/WriteFolderAdapter.kt
  app/src/main/java/com/daily/dayo/write/adapter/WriteUploadImageListAdapter.kt
  app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderAddViewModel.kt
  app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderViewModel.kt
  app/src/main/res/drawable/ic_order_change.xml
  app/src/main/res/layout/fragment_folder_setting.xml
  app/src/main/res/layout/fragment_folder_setting_add.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/fragment_my_profile_option.xml
  app/src/main/res/layout/fragment_write_folder.xml
  app/src/main/res/layout/item_folder_list.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#87 #81 [feature] WriteFolderFragment
  app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderAddFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/write/adapter/WriteFolderAdapter.kt
  app/src/main/java/com/daily/dayo/write/adapter/WriteUploadImageListAdapter.kt
  app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderAddViewModel.kt
  app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderViewModel.kt
  app/src/main/res/layout/fragment_write_folder.xml
  app/src/main/res/layout/item_folder_list.xml
Labels: feature

#90 #81 [layout] FolderSettingFragment
  app/src/main/java/com/daily/dayo/profile/FolderSettingFragment.kt
  app/src/main/java/com/daily/dayo/profile/adapter/FolderSettingAdapter.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/FolderSettingViewModel.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt
Labels: feature

#91 #89 [feature] PostFragment
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/network/Post/PostApiHelper.kt
  app/src/main/java/com/daily/dayo/network/Post/PostApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/Post/PostApiService.kt
  app/src/main/java/com/daily/dayo/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/post/SwipeHelperCallback.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostImageSliderAdapter.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostTagListAdapter.kt
  app/src/main/java/com/daily/dayo/post/model/ResponsePost.kt
  app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt
  app/src/main/java/com/daily/dayo/repository/PostRepository.kt
  app/src/main/res/drawable/ic_indicator_active.xml
  app/src/main/res/drawable/ic_indicator_inactive.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_post_comment.xml
  app/src/main/res/layout/item_post_image_slider.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#100 #85 [feature] WriteFragment Write
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/network/write/WriteApiHelper.kt
  app/src/main/java/com/daily/dayo/network/write/WriteApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/write/WriteApiService.kt
  app/src/main/java/com/daily/dayo/repository/WriteRepository.kt
  app/src/main/java/com/daily/dayo/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt
  app/src/main/java/com/daily/dayo/write/model/Write.kt
  app/src/main/java/com/daily/dayo/write/viewmodel/WriteOptionViewModel.kt
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_main_post.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#101 #99 [feature] Get Member Info
  app/src/main/java/com/daily/dayo/SharedManager.kt
  app/src/main/java/com/daily/dayo/User.kt
  app/src/main/java/com/daily/dayo/di/NetworkModule.kt
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/login/LoginActivity.kt
  app/src/main/java/com/daily/dayo/login/LoginRepository.kt
  app/src/main/java/com/daily/dayo/login/LoginViewModel.kt
  app/src/main/java/com/daily/dayo/login/MemberResponse.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt
  app/src/main/java/com/daily/dayo/network/login/LoginApiHelper.kt
  app/src/main/java/com/daily/dayo/network/login/LoginApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/login/LoginApiService.kt
  app/src/main/java/com/daily/dayo/network/login/LoginServiceImpl.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/FolderSettingViewModel.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt
  app/src/main/java/com/daily/dayo/write/WriteFolderAddFragment.kt
  app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderViewModel.kt
Labels: feature

#103 #98 [feature] Write Comment, Read Comment List
  app/src/main/java/com/daily/dayo/network/Post/PostApiHelper.kt
  app/src/main/java/com/daily/dayo/network/Post/PostApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/Post/PostApiService.kt
  app/src/main/java/com/daily/dayo/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt
  app/src/main/java/com/daily/dayo/post/model/PostComment.kt
  app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt
  app/src/main/java/com/daily/dayo/repository/PostRepository.kt
  app/src/main/res/layout/item_post_comment.xml
Labels: feature

#106 #104 [layout] MyProfileFragment
  app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/ProfileBookmarkPostListFragment.kt
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/fragment_profile_bookmark_post_list.xml
Labels: layout

#107 #105 [feature] Delete Post, Delete PostComment
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/network/post/PostApiHelper.kt
  app/src/main/java/com/daily/dayo/network/post/PostApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/post/PostApiService.kt
  app/src/main/java/com/daily/dayo/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/post/PostOptionMineFragment.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt
  app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt
  app/src/main/java/com/daily/dayo/repository/PostRepository.kt
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/fragment_post_option_mine.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#111 #97 [feature] FolderFragment, FolderOptionFragment
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt
  app/src/main/java/com/daily/dayo/profile/FolderFragment.kt
  app/src/main/java/com/daily/dayo/profile/FolderOptionFragment.kt
  app/src/main/java/com/daily/dayo/profile/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/model/Folder.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/FolderOptionViewModel.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/FolderViewModel.kt
  app/src/main/java/com/daily/dayo/repository/FolderRepository.kt
  app/src/main/java/com/daily/dayo/util/DefaultDialog.kt
  app/src/main/res/drawable/ic_option_horizontal_white.xml
  app/src/main/res/layout/dialog_defalt_explanation_confirm.xml
  app/src/main/res/layout/fragment_folder.xml
  app/src/main/res/layout/fragment_folder_option.xml
  app/src/main/res/layout/item_folder_post.xml
  app/src/main/res/layout/item_profile_folder.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#116 #109 [layout] Signup with Email
  app/src/main/java/com/daily/dayo/login/LoginActivity.kt
  app/src/main/java/com/daily/dayo/login/LoginFragment.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordConfirmationFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/util/ButtonActivation.kt
  app/src/main/java/com/daily/dayo/util/HideKeyBoardUtil.kt
  app/src/main/res/drawable/button_default_signup_next_button_active.xml
  app/src/main/res/drawable/button_default_signup_next_button_inactive.xml
  app/src/main/res/drawable/ic_check_ok_sign.xml
  app/src/main/res/drawable/ic_check_x_sign.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup_email_set_email_address.xml
  app/src/main/res/layout/fragment_signup_email_set_password.xml
  app/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml
  app/src/main/res/layout/fragment_signup_email_set_profile.xml
  app/src/main/res/navigation/nav_graph_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: layout

#118 #110 [feature] MyProfileFragment, MyProfileEditImageOptionFragment
  app/src/main/java/com/daily/dayo/di/NetworkModule.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelper.kt
  app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/profile/ProfileApiService.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt
  app/src/main/java/com/daily/dayo/post/adapter/PostImageSliderAdapter.kt
  app/src/main/java/com/daily/dayo/profile/FolderFragment.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/OtherProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt
  app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordFragment.kt
Labels: feature

#121 #120 [layout] Improving Signup with Email
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordConfirmationFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileFragment.kt
  app/src/main/res/layout/fragment_signup_email_set_email_address.xml
  app/src/main/res/layout/fragment_signup_email_set_password.xml
  app/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml
  app/src/main/res/layout/fragment_signup_email_set_profile.xml
Labels: layout

#122 #117 [feature] Signup with Email
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileImageOptionFragment.kt
  app/src/main/res/layout/fragment_signup_email_set_profile_image_option.xml
  app/src/main/res/navigation/nav_graph_login.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/filepaths.xml
Labels: feature

#123 #119 [bug] Error occurs when only one thing is changed in MyProfileEditFragment
  app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt
  app/src/main/java/com/daily/dayo/util/ButtonActivation.kt
Labels: bug

#125 #124 [feature] HomePostItem
  app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt
  app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt
  app/src/main/java/com/daily/dayo/repository/HomeRepository.kt
  app/src/main/java/com/daily/dayo/util/GridSpacingItemDecoration.kt
  app/src/main/res/drawable/ic_like_default.xml
  app/src/main/res/layout/fragment_dayo_pick_post_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_main_post.xml
Labels: feature

#127 #126 [feature] HomeFragment Post List
  app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt
  app/src/main/java/com/daily/dayo/repository/HomeRepository.kt
  app/src/main/res/values/strings.xml
Labels: feature

#128 #112 [feature] FolderEditFragment
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt
  app/src/main/java/com/daily/dayo/profile/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/profile/FolderFragment.kt
  app/src/main/java/com/daily/dayo/profile/FolderOptionFragment.kt
  app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt
  app/src/main/java/com/daily/dayo/profile/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/profile/model/Folder.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/FolderEditViewModel.kt
  app/src/main/java/com/daily/dayo/repository/FolderRepository.kt
  app/src/main/res/layout/fragment_folder.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#130 #129 [feature] PostItem Like, Share, etc
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt
  app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt
  app/src/main/java/com/daily/dayo/network/post/PostApiHelper.kt
  app/src/main/java/com/daily/dayo/network/post/PostApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/post/PostApiService.kt
  app/src/main/java/com/daily/dayo/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/post/model/ResponsePost.kt
  app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt
  app/src/main/java/com/daily/dayo/repository/HomeRepository.kt
  app/src/main/java/com/daily/dayo/repository/PostRepository.kt
  app/src/main/res/drawable/edittext_background_post_comment_write.xml
  app/src/main/res/drawable/ic_bookmark_checked.xml
  app/src/main/res/drawable/ic_bookmark_default.xml
  app/src/main/res/drawable/ic_post_like_checked.xml
  app/src/main/res/drawable/selector_bookmark.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_feed_post.xml
  app/src/main/res/layout/item_post_comment.xml
Labels: feature, layout

#134 #114 [feature] FollowFragment
  app/src/main/java/com/daily/dayo/di/ServiceModule.kt
  app/src/main/java/com/daily/dayo/follow/FollowFragment.kt
  app/src/main/java/com/daily/dayo/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/follow/FollowingListFragment.kt
  app/src/main/java/com/daily/dayo/follow/adapter/FollowListAdapter.kt
  app/src/main/java/com/daily/dayo/follow/viewmodel/FollowViewModel.kt
  app/src/main/java/com/daily/dayo/network/follow/FollowApiHelper.kt
  app/src/main/java/com/daily/dayo/network/follow/FollowApiHelperImpl.kt
  app/src/main/java/com/daily/dayo/network/follow/FollowApiService.kt
  app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/OtherProfileFragment.kt
  app/src/main/java/com/daily/dayo/profile/model/Follow.kt
  app/src/main/java/com/daily/dayo/profile/viewmodel/OtherProfileViewModel.kt
  app/src/main/java/com/daily/dayo/repository/FollowRepository.kt
  app/src/main/res/drawable/edittext_background_follow_search.xml
  app/src/main/res/layout/fragment_follower_list.xml
  app/src/main/res/layout/fragment_following_list.xml
  app/src/main/res/layout/item_follow.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature
