Repository Daily-DAYO/DAYO_Android, pull requests merged in 2022-10, with the labels that each got.

#311 #306 [bug] Fix Notification Error While App Is Running
  app/build.gradle
  app/src/main/java/com/daily/dayo/data/datasource/remote/firebase/FirebaseMessagingService.kt
Labels: bug

#310 #286 [layout] Update Post Fragment Layout
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionMineFragment.kt
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/layout/item_feed_post.xml
  app/src/main/res/values/strings.xml
Labels: layout

#314 #313 [bug] Missing import statement
  app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt
Labels: bug

#316 #315 [refactoring] Change to minSdkVersion 26
  app/build.gradle
Labels: refactoring

#320 #319 [bug] Fix Follower, Following Empty View
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/FollowViewModel.kt
  app/src/main/res/layout/fragment_follow.xml
  app/src/main/res/layout/fragment_follower_list.xml
  app/src/main/res/layout/fragment_following_list.xml
Labels: bug

#321 #317 [feature] Change update profile api
  app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt
  app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/member/RequestUpdateMyProfileUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt
Labels: feature

#326 #325 [layout] Create Base AlertDialog
  app/src/main/java/com/daily/dayo/common/dialog/DefaultDialog.kt
  app/src/main/java/com/daily/dayo/common/dialog/LoadingAlertDialog.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionMineFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/res/drawable/background_white_radius_10.xml
  app/src/main/res/drawable/ic_dialog_loading.xml
  app/src/main/res/layout/dialog_loading_wait.xml
  app/src/main/res/values/strings.xml
Labels: layout
