Repository Daily-DAYO/DAYO_Android, pull requests merged in 2023-03, with the labels that each got.

#358 #357 [bug] post's comment box is out of bounds
  app/src/main/res/layout/fragment_post.xml
Labels: bug

#360 #359 [bug] Fix Crash issue at signupEmailSetProfileFragment
  app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt
  app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/member/RequestSignUpEmailUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
Labels: bug

#361 #356 [bug] fix kakao login
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt
Labels: bug

#363 #362 [feature] Check Nickname is duplicated at signupFragment
  app/src/main/java/com/daily/dayo/common/dialog/LoadingAlertDialog.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt
  app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/member/RequestCheckNicknameDuplicateUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
Labels: feature

#366 [doc] update Readme.md
  README.md
Labels: documentation

#368 #367 [feature] Add camera options when adding pictures
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt
  app/src/main/res/drawable/dialog_option_default_mid.xml
  app/src/main/res/layout/fragment_folder_setting_edit_image_option.xml
  app/src/main/res/layout/fragment_profile_edit_image_option.xml
Labels: feature, layout
