Repository Daily-DAYO/DAYO_Android, pull requests merged in 2023-07, with the labels that each got.

#407 #406 [refactoring] Remove unnecessary dispatchers and Change coroutine scope
  app/src/main/java/com/daily/dayo/data/di/CoroutinesDispatchersModule.kt
  app/src/main/java/com/daily/dayo/data/di/CoroutinesQualifiers.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/BlockListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FollowListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/PostCommentAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileBookmarkPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileLikePostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt
Labels: refactoring

#411 #410 [refactoring] Change diffUtil Logic
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FolderSettingAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileBookmarkPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileLikePostListAdapter.kt
Labels: bug, refactoring

#389 #375 [bug] Modify Search Results Count
  app/src/main/java/com/daily/dayo/data/datasource/remote/search/SearchResponse.kt
  app/src/main/java/com/daily/dayo/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/SearchRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/search/RequestSearchTotalCountUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/SearchViewModel.kt
Labels: bug

#419 #412 Add Clean up Post Detail logic when postFragment is destroyed
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/PostViewModel.kt
Labels: bug

#423 #422 [bug] Not Visible Folder Option Button
  app/src/main/java/com/daily/dayo/data/mapper/FolderMapper.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
Labels: bug

#425 #424 [feature] Confirm Duplication Nickname
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt
Labels: feature

#426 #414 Change tag limit, counting logic
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_write_tag.xml
  app/src/main/res/values/strings.xml
Labels: bug, refactoring

#427 #415 Fix different height of tag elements
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
Labels: bug, layout

#428 #417 change when dialog disappears when leaving the folder fragment
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderFragment.kt
Labels: bug

#429 #416 Change displaying limit toast message logic
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
Labels: bug

#420 #408 [bug] change profile follow button logic
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/res/drawable/button_follow_green.xml
  app/src/main/res/drawable/button_follow_white.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: bug, feature

#430 #418 [bug] Update Following and Following Fragment
  app/src/main/java/com/daily/dayo/presentation/adapter/FollowListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/FollowViewModel.kt
  app/src/main/res/layout/fragment_follow.xml
  app/src/main/res/layout/item_follow.xml
Labels: bug

#433 #432 [feature] Change Profile Request Api in MyProfileFragment
  app/src/main/java/com/daily/dayo/data/mapper/ProfileMapper.kt
  app/src/main/java/com/daily/dayo/domain/model/Profile.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt
Labels: feature

#434 #431 [chore] Set Base Url
  app/build.gradle
  app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt
  app/src/main/java/com/daily/dayo/data/di/NetworkModule.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/policy/PolicyFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
Labels: feature, chore

#441 #440 [feature] Change FCM Logic
  app/src/main/java/com/daily/dayo/data/datasource/local/SharedManager.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/firebase/FirebaseMessagingService.kt
  app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/member/RegisterFcmTokenUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/activity/LoginActivity.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/notification/SettingNotificationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/SettingNotificationViewModel.kt
Labels: feature

#442 #435 [refactoring] Change thread networking when uploading post
  app/src/main/java/com/daily/dayo/DayoApplication.kt
  app/src/main/java/com/daily/dayo/common/ConvertBitmap.kt
  app/src/main/java/com/daily/dayo/common/ConvertPx.kt
  app/src/main/java/com/daily/dayo/common/ListLiveData.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_write_option.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#444 [bug] Fix glide exception `Cannot obtain size for recycled Bitmap`
  app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/BlockListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FollowListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/PostCommentAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileBookmarkPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFolderListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/ProfileLikePostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/SearchTagResultPostAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt
Labels: bug

#445 #443 [layout] SearchResultFragment RecyclerView
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/item_search_result_post.xml
Labels: feature, layout

#447 [feature] Add Glide Memory Handling (missing part)
  app/src/main/java/com/daily/dayo/DayoApplication.kt
Labels: feature

#449 [bug] Fix delayed reaction occurs when the reaction button is clicked
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/FeedViewModel.kt
  app/src/main/res/layout/item_feed_post.xml
Labels: bug

#453 #452 [bug] Remove Invalid Import in CoroutinesDispatchersModule
  app/src/main/java/com/daily/dayo/data/di/CoroutinesDispatchersModule.kt
Labels: bug

#455 #454 [bug] Remove SearchResultFragment Argument
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: bug

#461 [bug] Scroll position not saved when returned from Post Fragment
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt
Labels: bug

#465 #464 [chore] Set MinifyEnabled
  app/build.gradle
  app/proguard-rules.pro
Labels: chore

#468 [bug] Fix Fix incorrectly merged file
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/daily/dayo/presentation/activity/MainActivity.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/notification/SettingNotificationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/res/values/strings.xml
Labels: bug
