Repository Daily-DAYO/DAYO_Android, pull requests merged in 2023-08, with the labels that each got.

#471 Merge changes from main branch
  README.md
  app/build.gradle
Labels: chore

#472 [bug] Fix private folder flag is not visible
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/layout/item_profile_folder.xml
Labels: bug

#476 #475 [bug] Don't validate when keeping nickname
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/res/values/strings.xml
Labels: bug

#481 [chore] Update kotlin, dependency, JVM version
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: chore

#483 Provide List of users who liked a particular post with jetpack compose
  app/src/main/java/com/daily/dayo/common/ConvertDP.kt
  app/src/main/java/com/daily/dayo/common/extension/ModifierExtension.kt
  app/src/main/java/com/daily/dayo/common/extension/NavControllerExtension.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/heart/HeartApiService.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/heart/HeartPostUsersPagingSource.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/heart/HeartResponse.kt
  app/src/main/java/com/daily/dayo/data/mapper/HeartMapper.kt
  app/src/main/java/com/daily/dayo/data/repository/HeartRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/model/LikeUser.kt
  app/src/main/java/com/daily/dayo/domain/repository/HeartRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/like/RequestPostLikeUsersUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostLikeUsersFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/PostViewModel.kt
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, layout

#486 [bug] Fix image with unsupported extensions being uploaded.
  app/src/main/java/com/daily/dayo/common/image/ImageResizeUtil.kt
  app/src/main/java/com/daily/dayo/common/image/ImageUploadUtil.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
  app/src/main/res/values/strings.xml
Labels: bug

#488 [bug] Fix scrolling to the top
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
Labels: bug

#490 [feature] Disable viewing the likes list function when no one likes that post
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/res/layout/fragment_post.xml
Labels: feature

#492 [bug] Some codes are missing else condition in when statement
  app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/SettingNotificationViewModel.kt
Labels: bug

#494 [bug] Change Lottie file
  app/src/main/res/raw/like_small.json
Labels: bug

#480 #477 [feature] Change to include emoticons in folder titles
  app/src/main/java/com/daily/dayo/common/TextUtil.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderAddFragment.kt
  app/src/main/res/layout/fragment_folder_setting_add.xml
  app/src/main/res/layout/fragment_write_folder_add.xml
Labels: feature

#496 [bug] Fix updated folder is not refreshed and displayed other user's information
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/FolderViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: bug

#499 #482 [feature] Add Image Indicator in FeedPostItem
  app/src/main/java/com/daily/dayo/data/datasource/remote/post/PostResponse.kt
  app/src/main/java/com/daily/dayo/data/mapper/PostMapper.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/res/layout/item_feed_post.xml
Labels: feature

#498 #497 [feature] Set folder subheading limit
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/res/layout/fragment_folder_setting_add.xml
Labels: feature

#501 [feature] Add Refreshing when bottom navigation bar icon is clicked
  presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/notification/NotificationFragment.kt
Labels: feature

#508 [feature] Add Firebase Crashlytics, Analytics
  app/build.gradle
  app/src/main/java/com/daily/dayo/DayoApplication.kt
  build.gradle
  presentation/build.gradle
Labels: feature

#510 [feature] Create Android CI
  .github/workflows/android-ci.yml
  app/build.gradle
Labels: feature

#512 [bug] Add code to exclude obfuscation related to networking
  app/proguard-rules.pro
Labels: bug
