Repository Daily-DAYO/DAYO_Android, pull requests merged in 2023-06, with the labels that each got.

#380 #379 [layout] Create Information Layout
  app/src/main/java/com/daily/dayo/common/extension/NavControllerExtension.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/information/InformationFragment.kt
  app/src/main/res/layout/fragment_information.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#382 #376 [feature] Set Screen Orientation to Portrait
  app/src/main/AndroidManifest.xml
Labels: feature

#383 #371 [feature] Folder Post List to Paging Adapter
  app/src/main/java/com/daily/dayo/data/datasource/remote/folder/FolderApiService.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/folder/FolderPagingSource.kt
  app/src/main/java/com/daily/dayo/data/datasource/remote/folder/FolderResponse.kt
  app/src/main/java/com/daily/dayo/data/mapper/FolderMapper.kt
  app/src/main/java/com/daily/dayo/data/repository/FolderRepositoryImpl.kt
  app/src/main/java/com/daily/dayo/domain/model/Folder.kt
  app/src/main/java/com/daily/dayo/domain/repository/FolderRepository.kt
  app/src/main/java/com/daily/dayo/domain/usecase/folder/RequestFolderInfoUseCase.kt
  app/src/main/java/com/daily/dayo/domain/usecase/folder/RequestFolderPostListUseCase.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/FolderSettingViewModel.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/FolderViewModel.kt
  app/src/main/res/layout/fragment_folder.xml
Labels: feature

#384 #381 [feature] Create Post Image DoubleTap Action - Like Post
  app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/res/layout/item_post_image_slider.xml
  app/src/main/res/raw/like_big.json
Labels: feature

#387 [bug] Fix fade animation is appeared when refreshing posts
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
Labels: bug

#388 #385 [feature] Create Small Like Animation in Home
  app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt
  app/src/main/res/drawable/ic_like_default.xml
  app/src/main/res/drawable/ic_like_pressed.xml
  app/src/main/res/layout/item_main_post.xml
  app/src/main/res/raw/like_small.json
Labels: bug, feature, layout

#391 #390 [bug] Back Button In SettingBlockFragment
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt
  app/src/main/res/layout/fragment_setting_block.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: bug

#395 #394 [feature] Add App Version Name
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/information/InformationFragment.kt
  app/src/main/res/layout/fragment_information.xml
Labels: feature

#397 #396 [feature] Change Image options
  app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
Labels: feature

#399 #398 [layout] Create notice list page layout
  app/src/main/java/com/daily/dayo/common/CustomDividerDecoration.kt
  app/src/main/java/com/daily/dayo/common/TimeChangerUtil.kt
  app/src/main/java/com/daily/dayo/domain/model/Notice.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/NoticeListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/notice/NoticeListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/viewmodel/NoticeViewModel.kt
  app/src/main/res/layout/fragment_notice_list.xml
  app/src/main/res/layout/item_notice_post.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#402 #401 [bug] Fix Network error toast message is always displayed when not logged in app
  app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
Labels: bug

#403 #400 [bug] Fix Profile MemberId Value
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
Labels: bug

#405 #404 [layout] Create empty view at home
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  app/src/main/res/drawable/background_white_radius_32.xml
  app/src/main/res/drawable/ic_home_empty.xml
  app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml
  app/src/main/res/layout/fragment_home_new_post_list.xml
  app/src/main/res/values/strings.xml
Labels: layout

#409 [bug] Change Trim bugs
  app/src/main/java/com/daily/dayo/common/ReplaceUnicode.kt
  app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCheckEmailCertificateFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCheckEmailFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordConfirmationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginEmailFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetEmailAddressFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetPasswordConfirmationFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetPasswordFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordCurrentFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordNewFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderAddFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt
  app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
Labels: bug, refactoring
