Repository Daily-DAYO/DAYO_Android, pull requests merged in 2024-06, with the labels that each got.

#566 #558 [layout] Search Post Hashtag Screen
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/post/PostLikeUsersScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/post/PostNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchPostHashtagScreen.kt
  presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/FeedViewModel.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/SearchViewModel.kt
  presentation/src/main/res/drawable/ic_swap_vertical.xml
Labels: layout

#570 [feature] Add Application Force Update
  presentation/build.gradle
  presentation/src/main/java/daily/dayo/presentation/activity/LoginActivity.kt
  presentation/src/main/java/daily/dayo/presentation/common/dialog/DefaultDialog.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#574 [refactoring] Separate App with build type
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: refactoring

#572 [bug] Fix wrong login fail message
  presentation/src/main/java/daily/dayo/presentation/fragment/account/signin/LoginEmailFragment.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/AccountViewModel.kt
Labels: bug

#575 [layout] Fix Setting User Information
  presentation/src/main/java/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCompleteFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordCurrentFragment.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/AccountViewModel.kt
  presentation/src/main/res/layout/fragment_find_account_password_check_email.xml
  presentation/src/main/res/layout/fragment_find_account_password_check_email_certificate.xml
  presentation/src/main/res/layout/fragment_find_account_password_complete.xml
  presentation/src/main/res/layout/fragment_find_account_password_new_password.xml
  presentation/src/main/res/layout/fragment_find_account_password_new_password_confirmation.xml
  presentation/src/main/res/layout/fragment_login_email.xml
  presentation/src/main/res/layout/fragment_profile_edit.xml
  presentation/src/main/res/layout/fragment_setting_change_password_current.xml
  presentation/src/main/res/layout/fragment_setting_change_password_new.xml
  presentation/src/main/res/layout/fragment_signup_email_set_email_address.xml
  presentation/src/main/res/layout/fragment_signup_email_set_email_address_certificate.xml
  presentation/src/main/res/layout/fragment_signup_email_set_password.xml
  presentation/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml
  presentation/src/main/res/layout/fragment_signup_email_set_profile.xml
Labels: bug, layout

#577 [bug] FIx Image Quality Degradation
  presentation/src/main/java/daily/dayo/presentation/adapter/BlockListAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/adapter/FollowListAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/adapter/PostCommentAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/adapter/SearchTagResultPostAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/common/GlideLoadUtil.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/post/PostFragment.kt
Labels: bug

#567 [layout] Post Report Dialog
  presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt
  presentation/src/main/java/daily/dayo/presentation/view/TextField.kt
  presentation/src/main/java/daily/dayo/presentation/view/dialog/BottomSheetDialog.kt
  presentation/src/main/java/daily/dayo/presentation/view/dialog/RadioButtonDialog.kt
  presentation/src/main/res/drawable/ic_menu_delete.xml
  presentation/src/main/res/drawable/ic_menu_edit.xml
  presentation/src/main/res/drawable/ic_menu_report.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, layout
