Repository Daily-DAYO/DAYO_Android, pull requests merged in 2025-05, with the labels that each got.

#642 Migrate Setting Blocked Users View from XML to Compose
  presentation/src/main/java/daily/dayo/presentation/adapter/BlockListAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileOptionFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MypageNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/profile/ProfileNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/profile/ProfileScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/BlockedUsersScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/java/daily/dayo/presentation/view/DropdownMenu.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/ProfileViewModel.kt
  presentation/src/main/res/drawable/ic_blocked_users_empty.xml
  presentation/src/main/res/drawable/ic_menu_block.xml
  presentation/src/main/res/layout/fragment_setting_block.xml
  presentation/src/main/res/layout/item_block.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: refactoring

#648 Prevent home screen flickering
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeDayoPickScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeNewScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/HomeViewModel.kt
Labels: bug

#646 Update Compose and compileSdk version, migrate deprecated APIs
  README.md
  app/build.gradle
  build.gradle
  data/build.gradle
  presentation/build.gradle
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/java/daily/dayo/presentation/view/Button.kt
  presentation/src/main/java/daily/dayo/presentation/view/Chip.kt
  presentation/src/main/java/daily/dayo/presentation/view/Comment.kt
  presentation/src/main/java/daily/dayo/presentation/view/DetailPostView.kt
  presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt
  presentation/src/main/java/daily/dayo/presentation/view/HomePostView.kt
Labels: refactoring

#649 Migrate Application Notice View from XML to Compose
  data/src/main/java/daily/dayo/data/datasource/remote/notice/NoticeApiService.kt
  data/src/main/java/daily/dayo/data/datasource/remote/notice/NoticeResponse.kt
  data/src/main/java/daily/dayo/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/daily/dayo/domain/model/Notice.kt
  domain/src/main/java/daily/dayo/domain/repository/NoticeRepository.kt
  domain/src/main/java/daily/dayo/domain/usecase/notice/RequestDetailNoticeUseCase.kt
  presentation/src/main/java/daily/dayo/presentation/adapter/NoticeListAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/notice/NoticeDetailFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/notice/NoticeListFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/notice/NoticeDetailScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/notice/NoticeNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/notice/NoticesScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/NoticeViewModel.kt
  presentation/src/main/res/layout/fragment_notice_detail.xml
  presentation/src/main/res/layout/fragment_notice_list.xml
  presentation/src/main/res/layout/item_notice_post.xml
  presentation/src/main/res/navigation/nav_graph.xml
Labels: layout, refactoring
