Repository Daily-DAYO/DAYO_Android, pull requests merged in 2025-04, with the labels that each got.

#632 ProfileScreen
  presentation/src/main/java/daily/dayo/presentation/common/extension/ModifierExtension.kt
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeDayoPickScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeNewScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/FollowScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MypageNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/post/PostNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/post/PostScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/profile/ProfileNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/profile/ProfileScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchResultScreen.kt
  presentation/src/main/java/daily/dayo/presentation/view/Comment.kt
  presentation/src/main/java/daily/dayo/presentation/view/DetailPostView.kt
  presentation/src/main/java/daily/dayo/presentation/view/DropdownMenu.kt
  presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt
  presentation/src/main/java/daily/dayo/presentation/view/HomePostView.kt
  presentation/src/main/java/daily/dayo/presentation/view/dialog/CommentBottomSheetDialog.kt
  presentation/src/main/java/daily/dayo/presentation/view/dialog/ReportDialog.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/FolderViewModel.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/ProfileViewModel.kt
Labels: feature, layout

#630 Migrate Setting Notification View from XML to Compose
  presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/notification/SettingNotificationFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingNotificationScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/AccountViewModel.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/SettingNotificationViewModel.kt
  presentation/src/main/res/layout/fragment_setting_notification.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: layout

#634 Migrate Change Password View from XML to Compose
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordCurrentFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordNewFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/account/SetPasswordView.kt
  presentation/src/main/java/daily/dayo/presentation/screen/account/SignUpEmailScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/ChangePasswordScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/AccountViewModel.kt
  presentation/src/main/res/layout/fragment_setting_change_password_current.xml
  presentation/src/main/res/layout/fragment_setting_change_password_new.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: refactoring

#637 Add radius parameter to FilledRoundedCornerButton
  presentation/src/main/java/daily/dayo/presentation/view/Button.kt
Labels: refactoring

#638 Folder sorting and moving
  data/src/main/java/daily/dayo/data/datasource/remote/folder/FolderApiService.kt
  data/src/main/java/daily/dayo/data/datasource/remote/folder/FolderPagingSource.kt
  data/src/main/java/daily/dayo/data/datasource/remote/folder/FolderRequest.kt
  data/src/main/java/daily/dayo/data/mapper/FolderMapper.kt
  data/src/main/java/daily/dayo/data/repository/FolderRepositoryImpl.kt
  domain/src/main/java/daily/dayo/domain/model/Folder.kt
  domain/src/main/java/daily/dayo/domain/repository/FolderRepository.kt
  domain/src/main/java/daily/dayo/domain/usecase/folder/RequestFolderMoveUseCase.kt
  domain/src/main/java/daily/dayo/domain/usecase/folder/RequestFolderPostListUseCase.kt
  domain/src/main/java/daily/dayo/domain/usecase/folder/RequestOrderFolderUseCase.kt
  presentation/src/main/java/daily/dayo/presentation/adapter/FolderSettingAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/screen/folder/FolderPostMoveScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/folder/FolderScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MypageNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/write/WriteFolderScreen.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/FolderViewModel.kt
Labels: feature
