Repository Daily-DAYO/DAYO_Android, pull requests merged in 2025-03, with the labels that each got.

#625 Migrate Notification Views from XML to Compose
  data/src/main/java/daily/dayo/data/datasource/remote/alarm/AlarmApiService.kt
  data/src/main/java/daily/dayo/data/repository/AlarmRepositoryImpl.kt
  domain/src/main/java/daily/dayo/domain/model/Topic.kt
  domain/src/main/java/daily/dayo/domain/repository/AlarmRepository.kt
  domain/src/main/java/daily/dayo/domain/usecase/notification/MarkAlarmAsCheckedUseCase.kt
  presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt
  presentation/src/main/java/daily/dayo/presentation/adapter/NotificationListAdapter.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/notification/NotificationFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/notification/NotificationNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/notification/NotificationScreen.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/NotificationViewModel.kt
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/item_notification.xml
  presentation/src/main/res/menu/menu_main_bottom.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: layout

#626 SettingsScreen
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MypageNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/res/drawable/ic_next.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, layout

#629 [feature] Add customizable button texts, null cancel handling, and condional view rendering
  presentation/src/main/java/daily/dayo/presentation/view/dialog/ConfirmDialog.kt
Labels: feature
