Repository Daily-DAYO/DAYO_Android, pull requests merged in 2025-01, with the labels that each got.

#606 My Page Folder Screen
  data/src/main/java/daily/dayo/data/datasource/remote/post/PostApiService.kt
  data/src/main/java/daily/dayo/data/mapper/FolderMapper.kt
  data/src/main/java/daily/dayo/data/repository/PostRepositoryImpl.kt
  domain/src/main/java/daily/dayo/domain/model/Folder.kt
  domain/src/main/java/daily/dayo/domain/repository/PostRepository.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/folder/FolderOptionFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/mypage/folder/FolderSettingFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/folder/FolderCreateScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/folder/FolderEditScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/folder/FolderPostMoveScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/folder/FolderScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/mypage/MypageNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/view/Button.kt
  presentation/src/main/java/daily/dayo/presentation/view/Checkbox.kt
  presentation/src/main/java/daily/dayo/presentation/view/FolderView.kt
  presentation/src/main/java/daily/dayo/presentation/view/Switch.kt
  presentation/src/main/java/daily/dayo/presentation/view/dialog/ConfirmDialog.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/FolderViewModel.kt
  presentation/src/main/res/drawable/ic_folder_private_my_page.xml
  presentation/src/main/res/drawable/ic_folder_public_my_page.xml
  presentation/src/main/res/drawable/ic_menu_folder.xml
  presentation/src/main/res/drawable/ic_menu_post.xml
  presentation/src/main/res/drawable/ic_sort.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, layout

#610 [feature] Add KeyboardOptions, actions, and disable textField feature
  presentation/src/main/java/daily/dayo/presentation/view/TextField.kt
Labels: feature

#612 [feature] Add composable function for single photo selection via gallery/camera
  presentation/src/main/java/daily/dayo/presentation/common/image/ImageUploadUtil.kt
Labels: feature

#614 [layout] Add Dayo Loading Component
  presentation/src/main/java/daily/dayo/presentation/view/Loading.kt
  presentation/src/main/res/raw/dayo_loading.json
  presentation/src/main/res/values/strings.xml
Labels: layout

#615 Filter Feed by Category
  data/src/main/java/daily/dayo/data/datasource/remote/post/FeedPagingSource.kt
  data/src/main/java/daily/dayo/data/datasource/remote/post/PostApiService.kt
  data/src/main/java/daily/dayo/data/mapper/HeartMapper.kt
  data/src/main/java/daily/dayo/data/repository/HeartRepositoryImpl.kt
  data/src/main/java/daily/dayo/data/repository/PostRepositoryImpl.kt
  domain/src/main/java/daily/dayo/domain/model/Like.kt
  domain/src/main/java/daily/dayo/domain/repository/HeartRepository.kt
  domain/src/main/java/daily/dayo/domain/repository/PostRepository.kt
  domain/src/main/java/daily/dayo/domain/usecase/post/RequestFeedListUseCase.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/feed/FeedFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt
  presentation/src/main/java/daily/dayo/presentation/view/CategoryHorizontalGroup.kt
  presentation/src/main/java/daily/dayo/presentation/viewmodel/FeedViewModel.kt
Labels: feature
