Repository Daily-DAYO/DAYO_Android, pull requests merged in 2025-06, with the labels that each got.

#661 Fix showing initial search result when navigating back from later searches
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchResultScreen.kt
Labels: bug

#668 Fix Incorrect follow buttons shown for current user in likes list
  presentation/src/main/java/daily/dayo/presentation/screen/post/PostLikeUsersScreen.kt
Labels: bug

#669 Fix MainBottomNavigation layout
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
Labels: bug

#651 Migrate Application Information View from XML to Compose
  presentation/src/main/java/daily/dayo/presentation/fragment/policy/PolicyFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/SettingFragment.kt
  presentation/src/main/java/daily/dayo/presentation/fragment/setting/information/InformationFragment.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt
  presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/rules/RuleScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/AppInformationScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt
  presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt
  presentation/src/main/res/drawable/ic_chevron_r.xml
  presentation/src/main/res/layout/fragment_information.xml
  presentation/src/main/res/layout/fragment_policy.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: layout, refactoring

#657 Add Search history empty view
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchResultScreen.kt
  presentation/src/main/java/daily/dayo/presentation/screen/search/SearchScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: layout

#673 Add Network Error Dialog layout
  presentation/src/main/java/daily/dayo/presentation/view/dialog/NetworkErrorDialog.kt
  presentation/src/main/res/values/strings.xml
Labels: layout
